# Generated by Django 4.1.6 on 2023-02-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jharule', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hazard',
            new_name='Hazards',
        ),
        migrations.RenameModel(
            old_name='Step',
            new_name='Steps',
        ),
    ]
