# Generated by Django 4.1.6 on 2023-02-14 01:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jharule.models


class Migration(migrations.Migration):

    dependencies = [
        ('jharule', '0002_rename_hazard_hazards_rename_step_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('risk', models.TextField(max_length=500)),
                ('control', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='JobHazardDocument',
            fields=[
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=40, null=True)),
                ('activity', models.CharField(max_length=255)),
                ('author_first', models.CharField(max_length=35)),
                ('author_last', models.CharField(max_length=35)),
                ('supervisor_first', models.CharField(blank=True, max_length=35, null=True)),
                ('supervisor_last', models.CharField(blank=True, max_length=35, null=True)),
                ('date_reported', models.DateField()),
                ('last_updated', models.DateField(auto_now=True)),
                ('required_training', models.JSONField(blank=True, null=True)),
                ('required_ppe', models.JSONField(blank=True, null=True)),
                ('signatures', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('step_num', models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=jharule.models.Step.get_photo_path)),
                ('jha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jharule.jobhazarddocument')),
            ],
        ),
        migrations.RemoveField(
            model_name='steps',
            name='jha',
        ),
        migrations.DeleteModel(
            name='Hazards',
        ),
        migrations.DeleteModel(
            name='JobHazardDocuments',
        ),
        migrations.DeleteModel(
            name='Steps',
        ),
        migrations.AddField(
            model_name='hazard',
            name='step_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jharule.step'),
        ),
    ]
