# Generated by Django 4.1.6 on 2023-02-14 09:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jha.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobHazardDocument',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=40, null=True)),
                ('activity', models.CharField(max_length=255)),
                ('author_first', models.CharField(max_length=35)),
                ('author_last', models.CharField(max_length=35)),
                ('supervisor_first', models.CharField(blank=True, max_length=35, null=True)),
                ('supervisor_last', models.CharField(blank=True, max_length=35, null=True)),
                ('date_reported', models.DateField()),
                ('last_updated', models.DateField(auto_now=True)),
                ('required_training', models.JSONField(blank=True, null=True)),
                ('required_ppe', models.JSONField(blank=True, null=True)),
                ('signatures', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('step_num', models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=jha.models.Step.get_photo_path)),
                ('jha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jha.jobhazarddocument')),
            ],
        ),
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('risk', models.TextField(max_length=500)),
                ('control', models.TextField(max_length=500)),
                ('step_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jha.step')),
            ],
        ),
    ]
