# Generated by Django 4.1.6 on 2023-02-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='uid',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobhazarddocument',
            name='uid',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='step',
            name='uid',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
