# Generated by Django 4.1.6 on 2023-02-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jha', '0002_alter_hazard_uid_alter_jobhazarddocument_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobhazarddocument',
            name='author_first',
        ),
        migrations.RemoveField(
            model_name='jobhazarddocument',
            name='author_last',
        ),
        migrations.RemoveField(
            model_name='jobhazarddocument',
            name='supervisor_first',
        ),
        migrations.RemoveField(
            model_name='jobhazarddocument',
            name='supervisor_last',
        ),
        migrations.AddField(
            model_name='jobhazarddocument',
            name='author',
            field=models.CharField(default='First Last', max_length=70),
        ),
        migrations.AddField(
            model_name='jobhazarddocument',
            name='supervisor',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
