# Generated by Django 4.1.6 on 2023-02-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jha', '0003_remove_jobhazarddocument_author_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhazarddocument',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
