# Generated by Django 4.1.7 on 2023-02-22 03:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jharuler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobHazardDocument',
            fields=[
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=40, null=True)),
                ('activity', models.CharField(max_length=255)),
                ('author', models.CharField(default='First Last', max_length=70)),
                ('supervisor', models.CharField(blank=True, max_length=70, null=True)),
                ('date_reported', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('required_training', models.JSONField(blank=True, null=True)),
                ('required_ppe', models.JSONField(blank=True, null=True)),
                ('signatures', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('step_num', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to=jharuler.models.Step.get_photo_path)),
                ('jha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jharuler.jobhazarddocument')),
            ],
        ),
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('risk', models.TextField(max_length=500)),
                ('control', models.TextField(max_length=500)),
                ('step_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jharuler.step')),
            ],
        ),
    ]
